/* Consumeables */
let UCC = [
  "Dust of Disappearance",
  "Elemental Gem",
  "Oil of Slipperiness",
  "Philter of Love",
  "Potion of Animal Friendship",
  "Potion of Fire Breath",
  "Potion of Growth",
  "Potion of Hill Giant Strength",
  "Potion of Resistance",
  "Potion of Water Breathing",
  "Deck of Illusions",
  "Dust of Dryness",
  "Gem of Brightness",
  "Robe of Useful Items",
  "Wind Fan",
  "Keoghtom's Ointment",
  "Potion of Greater Healing",
  "Spell Scroll - 2nd Level",
  "Spell Scroll - 3rd Level",
  "Spellwrought Tattoo - 2nd Level",
  "Spellwrought Tattoo - 3rd Level",
  "Adrenal Booster",
  "Bottled Breath",
  "Bypass Spike",
  "Dust of Corrosion",
  "Elemental Grenade 1.0",
  "Ether Potion 2.0",
  "Explosive Ammunition 1.0",
  "Fragmentation Grenade 1.0",
  "Frenzy",
  "High Explosive Grenade 1.0",
  "Lemon Grenade",
  "Manual of Armor Proficiency",
  "Manual of Shield Mastery",
  "Manual of Weapon Mastery",
  "Perception Enhancer",
  "Pixie Dust",
  "Poison Cloud Grenade 1.0",
  "Potion of Advantage",
  "Rogue’s Assistant",
  "Spell infused ammunition - 2nd Level",
  "Spell infused ammunition - 3rd Level",
  "Stunning Grenade",
  "Stunning Strike",
  "Subsonic ammunition",
  "Truth Serum",
  "Adamantine Ammunition",
  "Dust of Deliciousness",
  "Paper Birds",
  "Waterskin of Voices",
];

let RAC = [
  "Elixir of Health",
  "Oil of Etherealness",
  "Potion of Clairvoyance",
  "Potion of Diminution",
  "Potion of Frost Giant Strength",
  "Potion of Stone Giant Strength",
  "Potion of Gaseous Form",
  "Potion of Heroism",
  "Potion of Invulnerability",
  "Potion of Mind Reading",
  "Quaal's Feather Token",
  "Scroll of Protection",
  "Bag of Beans",
  "Chime of Opening",
  "Horn of Blasting",
  "Potion of Fire Giant Strength",
  "Bead of Force",
  "Necklace of Fireballs",
  "Potion of Superior Healing",
  "Spell Scroll - 4th Level",
  "Spell Scroll - 5th Level",
  "Spellwrought Tattoo - 4th Level",
  "Spellwrought Tattoo - 5th Level",
  "Angry Lemon Grenade",
  "Assassin’s Sting",
  "Contagion Burst Grenade",
  "Elemental Grenade 2.0",
  "Ether Potion 3.0",
  "Explosive Ammunition 2.0",
  "Fragmentation Grenade 2.0",
  "High Explosive Grenade 2.0",
  "Kidnapper’s Friend",
  "Manual of Iron Skin",
  "Manual of the Iron Wall",
  "Manual of Fighting Style",
  "Paralyzing Strike",
  "Poison Cloud Grenade 2.0",
  "Potion of Aqueous Form",
  "Potion of Maximum Power",
  "Potion of Mind Control (Beast)",
  "Potion of Mind Control (Humanoid)",
  "Proficiency Chip",
  "Remedy",
  "Researcher’s Assistant",
  "Ring of Temporal Salvation",
  "Spell infused ammunition - 4th Level",
  "Spell infused ammunition - 5th Level",
  "Thermite Charge",
  "Ambrosia",
  "Chromatic Rose",
];

let VRC = [
  "Cave Johnson’s Personal Lemon Grenade",
  "Dispelling Stone",
  "Ether Potion 4.0",
  "Expertise Chip",
  "Holy Hand Grenade of Antioch",
  "Manual of a 1,000 Weapons",
  "Melange of Arrakis",
  "Potion of Bodily Health",
  "Potion of Clear Thought",
  "Potion of Gainful Exercise",
  "Potion of Mind Control (Monster)",
  "Potion of Leadership and Influence",
  "Potion of Possibility",
  "Potion of Quickness of Action",
  "Potion of Understanding",
  "Reincarnation Dust",
  "Spell infused ammunition - 6th Level",
  "Spell infused ammunition - 7th Level",
  "Spell infused ammunition - 8th Level",
  "Decanter of Endless Youth",
];

let LEC = [
  "Manual of Bodily Health",
  "Manual of Gainful Exercise",
  "Manual of Quickness of Action",
  "Potion of Storm Giant Strength",
  "Tome of Clear Thought",
  "Tome of Leadership and Influence",
  "Tome of Understanding",
  "Spell Scroll - 9th Level",
  "Spellwrought Tattoo - 9th Level",
  "Sovereign Glue",
  "Universal Solvent",
  "Ring of Three Wishes",
  "Ioun Stone, Greater Absorption",
  "Scarab of Protection",
  "Potion of Dragon's Majesty",
  "Potion of Giant Size",
  "Rejuvenate",
  "Scroll of the Comet",
  "Scroll of Saving Throws",
  "Spell infused ammunition - 9th Level",
];

/* Miscellaneous */
let UCM = [
  "Alchemy Jug",
  "Circlet of Blasting",
  "Figurine of Wondrous Power, Silver Raven",
  "Bag of Tricks",
  "Cap of Water Breathing",
  "Decanter of Endless Water",
  "Driftglobe",
  "Eversmoking Bottle",
  "Helm of Comprehending Languages",
  "Helm of Telepathy",
  "Immovable Rod",
  "Lantern of Revealing",
  "Medallion of Thoughts",
  "Periapt of Health",
  "Quiver of Ehlonna",
  "Ring of Mind Shielding",
  "Ring of Swimming",
  "Ring of Water Walking",
  "Rope of Climbing",
  "Saddle of the Cavalier",
  "Staff of the Adder",
  "Staff of the Python",
  "Bag of Holding",
  "Boots of Elvenkind",
  "Broom of Flying",
  "Cloak of the Manta Ray",
  "Eyes of Minute Seeing",
  "Gloves of Thievery",
  "Goggles of Night",
  "Hat of Disguise",
  "Instrument of the Bards, Uncommon",
  "Pearl of Power",
  "Slippers of Spider Climbing",
  "Wand of Magic Detection",
  "Wand of Magic Missiles",
  "Wand of Secrets",
  "Winged Boots",
  "Wand of the War Mage +1",
  "Barrier Tattoo (Small)",
  "Feywild Shard",
  "Guardian Emblem",
  "Nature's Mantle",
  "Slumbering Dragon-Touched Focus",
  "Slumbering Scaled Ornament",
  "Bandolier of the Gunslinger",
  "Pauldron of Lifestealing 1.0",
  "Rod of Retribution 1.0",
  "Skyblinder Staff",
  "All-Purpose Tool +1",
  "Amulet of the Devout +1",
  "Arcane Grimoire +1",
  "Bloodwell Vial +1",
  "Chronomancer’s Timekeeper +1",
  "Dragonhide Sash +1",
  "Monk’s Limb Wrappings +1",
  "Rhythm-Maker's Instrument +1",
  "Rod of the Pact Keeper +1",
  "Cowl of the Desperate Thief",
  "Mask of the Wild Hunt 1.0",
  "Amulet of Proof against Detection and Location",
  "Boots of Striding and Springing",
  "Eyes of Charming",
  "Gloves of Missile Snaring",
  "Gloves of Swimming and Climbing",
  "Necklace of Adaptation",
  "Ring of Jumping",
  "Cloak of Elvenkind",
  "Eyes of the Eagle",
  "Periapt of Wound Closure",
  "Wand of Web",
  "Boots of the Winterlands",
  "Brooch of Shielding",
  "Cloak of Protection",
  "Gauntlets of Ogre Power",
  "Headband of Intellect",
  "Ring of Warmth",
  "Stone of Good Luck",
  "Fighting Gloves +1",
  "Amulet of the Drunkard",
  "Badge of the Watch Guard 1.0",
  "Black Phial",
  "Bracelet of Counterspelling 1.0",
  "Gloves of Archery",
  "Concealed Holster",
  "Finder's Goggles 1.0",
  "Goggles of Object Reading",
  "Glamerweave 1.0",
  "Gloves of the crafter",
  "Hearthmead",
  "Helm of Underwater Action",
  "Mage’s Defense 1.0",
  "Pipes of the Sewers",
  "Pipes of Haunting",
  "Pyroconverger 1.0",
  "Ring of Obscuring",
  "Ring of Second Chances",
  "Ring of Truth Telling",
  "Slumbering Dragon Vessel",
  "Wand of Entangle",
  "Wizard's Bookmark",
];

let RAM = [
  "Bowl of Commanding Water Elementals",
  "Brazier of Commanding Fire Elementals",
  "Cape of the Mountebank",
  "Censer of Controlling Air Elementals",
  "Figurine of Wondrous Power, Rare",
  "Horn of Valhalla, Silver",
  "Iron Bands of Bilarro",
  "Stone of Controlling Earth Elementals",
  "Cloak of the Bat",
  "Daern's Instant Fortress",
  "Dimensional Shackles",
  "Folding Boat",
  "Horn of Valhalla, Brass",
  "Horseshoes of Speed",
  "Periapt of Proof against Poison",
  "Ring of Animal Influence",
  "Ring of X-ray Vision",
  "Rope of Entanglement",
  "Staff of Charming",
  "Staff of Healing",
  "Staff of Swarming Insects",
  "Staff of Withering",
  "Staff of the Woodlands",
  "Wand of the War Mage +2",
  "Boots of Levitation",
  "Helm of Teleportation",
  "Instrument of the Bards, Canaith Mandolin",
  "Instrument of the Bards, Cli Lyre",
  "Necklace of Prayer Beads",
  "Portable Hole",
  "Ring of Spell Storing",
  "Robe of Eyes",
  "Wings of Flying",
  "Barrier Tattoo (Medium)",
  "Alchemical Compendium",
  "Astral Shard",
  "Astromancy Archive",
  "Atlas of Endless Horizons",
  "Bell Branch",
  "Duplicitous Manuscript",
  "Elemental Essence Shard",
  "Far Realm Shard",
  "Fulminating Treatise",
  "Heart Weaver's Primer",
  "Libram of Souls and Flesh",
  "Lyre of Building",
  "Outer Essence Shard",
  "Planecaller's Codex",
  "Protective Verses",
  "Reveler's Concertina",
  "Shadowfell Shard",
  "Stirring Dragon-Touched Focus",
  "Stirring Scaled Ornament",
  "Bandolier of the Mysterious Stranger",
  "Bracers of Flying Weapons",
  "Pauldron of Lifestealing 2.0",
  "Rod of Retribution 2.0",
  "Spider Staff",
  "Staff of Defense",
  "All-Purpose Tool +2",
  "Amulet of the Devout +2",
  "Arcane Grimoire +2",
  "Bloodwell Vial +2",
  "Chronomancer’s Timekeeper +2",
  "Dragonhide Sash +2",
  "Monk’s Limb Wrappings +2",
  "Rhythm-Maker's Instrument +2",
  "Rod of the Pact Keeper +2",
  "Blessings of The Healer 1.0",
  "Cowl of the Seasoned Thief",
  "Mask of the Wild Hunt 2.0",
  "Staff of the Ivory Claw",
  "Rod of Rulership",
  "Gem of Seeing",
  "Ring of Feather Falling",
  "Ring of Free Action",
  "Ring of Resistance",
  "Ring of the Ram",
  "Tentacle Rod",
  "Amulet of Health",
  "Belt of Dwarvenkind",
  "Belt of Hill Giant Strength",
  "Boots of Speed",
  "Bracers of Defense",
  "Cloak of Displacement",
  "Cube of Force",
  "Ioun Stone, Awareness",
  "Ioun Stone, Protection",
  "Ioun Stone, Reserve",
  "Ioun Stone, Sustenance",
  "Mantle of Spell Resistance",
  "Ring of Evasion",
  "Ring of Protection",
  "Wand of Binding",
  "Wand of Enemy Detection",
  "Wand of Fear",
  "Wand of Fireballs",
  "Wand of Lightning Bolts",
  "Wand of Paralysis",
  "Wand of Wonder",
  "Fighting Gloves +2",
  "Badge of the Watch Guard 2.0",
  "Bracelet of Counterspelling 2.0",
  "Claws of the Umber Hulk",
  "Eagle Whistle",
  "Finder's Goggles 2.0",
  "Glamerweave 2.0",
  "Heward's Handy Haversack",
  "Mage’s Defense 2.0",
  "Mage’s Shield Pin 1.0",
  "Mizzium Mortar",
  "Opal of the Ild Rune",
  "Orb of the Stein Rune",
  "Pyroconverger 2.0",
  "Ring of the Mists",
  "Robe of Summer",
  "Siren Song Lyre",
  "Stirring Dragon Vessel",
  "Wand of Winter",
];

let VRM = [
  "Efreeti Bottle",
  "Figurine of Wondrous Power, Obsidian Steed",
  "Horn of Valhalla, Bronze",
  "Carpet of Flying",
  "Horseshoes of a Zephyr",
  "Rod of Security",
  "Staff of Fire",
  "Staff of Frost",
  "Staff of Power",
  "Staff of Striking",
  "Staff of Thunder and Lightning",
  "Wand of the War Mage +3",
  "Instrument of the Bards, Anstruth Harp",
  "Rod of Absorption",
  "Absorbing Tattoo",
  "Barrier Tattoo (Large)",
  "Ghost Step Tattoo",
  "Lifewell Tattoo",
  "Cauldron of Rebirth",
  "Crystalline Chronicle",
  "Wakened Dragon-Touched Focus",
  "Wakened Scaled Ornament",
  "Bandolier of the East and West",
  "Gauntlets of Battle Prowess",
  "Eldritch Staff",
  "Ingot of the Skold Rune",
  "Pauldron of Lifestealing 3.0",
  "Mask of the Pale Stalker",
  "Peregrine Mask",
  "Robe of Stars",
  "Rod of Retribution 3.0",
  "Staff of Fate",
  "Watchful Helm",
  "All-Purpose Tool +3",
  "Amulet of the Devout +3",
  "Arcane Grimoire +3",
  "Bloodwell Vial +3",
  "Chronomancer’s Timekeeper +3",
  "Dragonhide Sash +3",
  "Monk’s Limb Wrappings +3",
  "Rhythm-Maker's Instrument +3",
  "Rod of the Pact Keeper +3",
  "Ascendant Sorcerer’s Robes",
  "Blast Scepter",
  "Blessings of The Healer 2.0",
  "Barbarian’s Crown",
  "Cowl of the Master Thief",
  "Mask of the Wild Hunt 3.0",
  "Ring of Magic Mastery",
  "Robe of the Enlightened Buddha",
  "Robe of the Infinite Wizard",
  "Staff of Dunamancy",
  "Twinning Cantrip Bracers",
  "Voyager Staff",
  "Belt of Frost Giant Strength",
  "Belt of Stone Giant Strength",
  "Cloak of Arachnida",
  "Crystal Ball",
  "Ring of Regeneration",
  "Ring of Telekinesis",
  "Belt of Fire Giant Strength",
  "Helm of Brilliance",
  "Ioun Stone, Agility",
  "Ioun Stone, Fortitude",
  "Ioun Stone, Insight",
  "Ioun Stone, Intellect",
  "Ioun Stone, Leadership",
  "Ioun Stone, Strength",
  "Rod of Alertness",
  "Wand of Polymorph",
  "Fighting Gloves +3",
  "Amethyst Lodestone",
  "Anti-Charmed Charm",
  "Arcane Cannon",
  "Armband of the Awakened",
  "Badge of the Watch Guard 3.0",
  "Bandana of Courage",
  "Bracelet of Counterspelling 3.0",
  "Boots of the Hardened Adventurer",
  "Cuffs of Prevention",
  "Diadem of Medusa",
  "Finder's Goggles 3.0",
  "Glamerweave 3.0",
  "Mage’s Defense 3.0",
  "Mage’s Shield Pin 2.0",
  "Necklace of Action",
  "Preventative Earrings",
  "Protective Eyewear",
  "Pyroconverger 3.0",
  "Ring of Continuous Action",
  "Ring of Shooting Stars",
  "Robe of Scintillating Colors",
  "Shard of the Ise Rune",
  "Star Pendant",
  "Undergarments of Protection",
  "Wakened Dragon Vessel",
  "Wand of Polymorph",
  "Player Choice x1 Uncommon",
  "Player Choice x1 Rare",
  "Player Choice x1 Very Rare",
];

let LEM = [
  "Horn of Valhalla, Iron",
  "Iron Flask",
  "Apparatus of Kwalish",
  "Instrument of the Bards, Ollamh Harp",
  "Sphere of Annihilation",
  "Blood Fury Tattoo",
  "Ascendant Dragon-Touched Focus",
  "Ascendant Scaled Ornament",
  "Ascendant Dragon Vessel",
  "Chromatic Dragon Mask",
  "Gem Dragon Mask",
  "Gloves of Soul Catching",
  "Metallic Dragon Mask",
  "Robe of the Archmagi",
  "Ruby Weave Gem",
  "Staff of the Magi",
  "Ring of Djinni Summoning",
  "Belt of Cloud Giant Strength",
  "Crystal Ball (Legendary Version)",
  "Ring of Elemental Command",
  "Talisman of the Sphere",
  "Cloak of Invisibility",
  "Ioun Stone, Mastery",
  "Ioun Stone, Regeneration",
  "Ring of Invisibility",
  "Ring of Spell Turning",
  "Rod of Resurrection",
  "Belt of Storm Giant Strength",
  "Gold Canary Figurine of Wondrous Power",
  "Platinum Scarf",
  "Spell Bottle",
];

/* Weapons */
let UCW = [
  "Ammunition +1",
  "Weapon +1",
  "Slumbering Dragon's Wrath",
  "Bard’s Conductor +1",
  "Bladesinger’s Performance +1",
  "Chaplain’s Crozius +1",
  "Far Strider’s Weapon +1",
  "Hexblade Weapon +1",
  "Moon Weapon +1",
  "Smiting Special +1",
  "Tools of War +1",
  "Elemental Thrower",
  "Blindsight 1.0",
  "Bloody 1.0",
  "Elemental Damage 1.0",
  "Focused",
  "Life Stealing 1.0",
  "Merciful",
  "Speed Loader 1.0",
  "Venom 1.0",
  "Vicious 1.0",
  "Warning",
  "Adamantine Weapon",
  "Flintlock Revolver System 1.0",
  "Mechanical Revolver System 1.0",
];

let RAW = [
  "Ammunition +2",
  "Weapon +2",
  "Stirring Dragon's Wrath",
  "Elemental Weapon +1",
  "Smart Weapon +1",
  "Bronntanas Weapon +2",
  "Crystal Weapon +2",
  "Dragon Wing Bow +2",
  "Sunforger +2",
  "Weapon of Terror +2",
  "Healing Weapon +1",
  "Bard’s Conductor +2",
  "Bladesinger’s Performance +2",
  "Chaplain’s Crozius +2",
  "Far Strider’s Weapon +2",
  "Hexblade Weapon +2",
  "Moon Weapon +2",
  "Smiting Special +2",
  "Tools of War +2",
  "(Creature Type) Slayer +1",
  "Elemental Thrower +1",
  "Flame Tongue +1",
  "Lightning Weapon +1",
  "Needlepoint +1",
  "Serpent's Fang +1",
  "Sun Weapon +1",
  "Weapon of Wounding +1",
  "Blindsight 2.0",
  "Bloody 2.0",
  "Elemental Damage 2.0",
  "Infinite",
  "Life Stealing 2.0",
  "Mangler",
  "Speed Loader 2.0",
  "Venom 2.0",
  "Vicious 2.0",
  "Flintlock Revolver System 2.0",
  "Mechanical Revolver System 2.0",
  "Magitek Firearm",
];

let VRW = [
  "Ammunition +3",
  "Weapon +3",
  "Wakened Dragon's Wrath",
  "Elemental Weapon +2",
  "Nine Lives Stealer +2",
  "Bronntanas Weapon +3",
  "Crystal Weapon +3",
  "Dancing Weapon +3",
  "Dragon Wing Bow +3",
  "Dwarven Thrower +3",
  "Sunforger +3",
  "Healing Weapon +2",
  "Bard’s Conductor +3",
  "Bladesinger’s Performance +3",
  "Far Strider’s Weapon +3",
  "Hexblade Weapon +3",
  "Moon Weapon +3",
  "Smiting Special +3",
  "Tools of War +3",
  "(Creature Type) Slayer +1",
  "Dusk Destroyer +2",
  "Elemental Thrower +2",
  "Flame Tongue +2",
  "Frost Brand +2",
  "Lightning Weapon +2",
  "Serpent's Fang +2",
  "Sun Weapon +2",
  "Weapon of Sharpness +2",
  "Weapon of Wounding +2",
  "Blindsight 3.0",
  "Bloody 3.0",
  "Elemental Damage 3.0",
  "Life Stealing 3.0",
  "Speed",
  "Speed Loader 3.0",
  "Venom 3.0",
  "Vicious 3.0",
];

let LEW = [
  "Ascendant Dragon's Wrath",
  "Bludgeon of Thunderbolts",
  "Defender",
  "Life-Eater",
  "Flail of Tiamat",
  "Rod of Lordly Might",
  "True Strike Weapon",
  "Holy Avenger",
  "Amethyst Annihilator",
  "Crystal Cadence",
  "Emerald Exterminator",
  "Luck Weapon",
  "Sapphire Sapper",
  "Topaz Terminator",
  "Vorpal Weapon",
];

/* Armor & Shields */
let UCAS = [
  "Shield +1",
  "Elven Light Armor",
  "Ablative 1.0",
  "Cameleoline Weaving 1.0",
  "Glamoured",
  "Hunter 1.0",
  "Mariner 1.0",
  "Mobility 1.0",
  "Resistance 1.0",
  "Adamantine Armor",
  "Magically Reinforced Leather",
  "Mithral Armor",
  "Pariah's Shield +1",
  "Battering Shield",
  "Counter 1.0",
  "Reactive 1.0",
  "Resistance 1.0",
  "Sentinel",
  "Unyielding 1.0",
  "Mithral Shield",
];

let RAAS = [
  "Armor +1",
  "Shield +2",
  "Magitek Armor +1",
  "Coat of the Duelist",
  "Elven Heavy Armor",
  "Elven Medium Armor",
  "Ablative 2.0",
  "Cameleoline Weaving 2.0",
  "Hunter 2.0",
  "Mariner 2.0",
  "Mobility 2.0",
  "Resistance 2.0",
  "Shape Changing",
  "Mizzium ",
  "Magically Reinforced Rockhide Leather",
  "Serpent Scale Armor",
  "Unwavering Defense +2",
  "Arrow-Catching",
  "Counter 2.0",
  "Reactive 2.0",
  "Resistance 2.0",
  "Unyielding 2.0",
  "Serpent Scale Shield",
];

let VRAS = [
  "Armor +2",
  "Shield +3",
  "Small Slayer Exoskeleton +1",
  "Titan Slayer Exoskeleton +1",
  "Magitek Armor +2",
  "Battle Master’s Armor +2",
  "Chaplain’s Vestments +2",
  "Creative Maestro’s Outfit +2",
  "Far Strider’s Armor +2",
  "Forest Guardian +2",
  "Guardian Protocol +2",
  "Master Rogue’s Armor +2",
  "Mother of Invention +2",
  "Pact Master’s Armor +2",
  "Time Lord’s Armor +2",
  "Ablative 3.0",
  "Cameleoline Weaving 3.0",
  "Dwarven Stubbornness",
  "Hunter 3.0",
  "Mariner 3.0",
  "Mobility 3.0",
  "Resistance 3.0",
  "Dragon Scale Armor",
  "The Last Guardian +3",
  "Animated",
  "Counter 3.0",
  "Reactive 3.0",
  "Resistance 3.0",
  "Spellguard",
  "Unyielding 3.0",
  "Dragon Scale Shield",
];

let LEAS = [
  "Armor +3",
  "Armor of Invulnerability +3",
  "Etherealness",
  "Efreeti Obsidian Armor",
];

/* Advanced Technology */
let UCAT = [
  "Blasting Eye 1.0",
  "Cat Eyes 1.0",
  "Dog Ears 1.0",
  "Elemental Projector Arm 1.0",
  "Fortified Ankles & Tendons 1.0",
  "Gorilla Arms 1.0",
  "Mantis Arm 1.0",
  "Pain Ward 1.0",
  "Quicksilver Legs 1.0",
  "Reflex Booster 1.0",
  "Resistance Booster 1.0",
  "Shapechanger 1.0",
  "Subdermal Armor 1.0",
  "Vocal Emulator",
  "Implant of Unstoppable Life",
  "Manipulator Mechadendrite 1.0",
  "Remembrance Implant",
  "Tool Mechadendrite 1.0",
  "Barrier Device 1.0",
  "Cyberdeck 2.0",
  "Grav Chute",
  "Scanner Device 1.0",
  "Stummer Device",
];

let RAAT = [
  "Ambidextrous Joint Enhancements",
  "Blasting Eye 2.0",
  "Bloodhound Nose",
  "Cat Eyes 2.0",
  "Cerebral Enhancements",
  "Dog Ears 2.0",
  "Elemental Projector Arm 2.0",
  "Fortified Ankles & Tendons 2.0",
  "Gastral Bionics",
  "Gorilla Arms 2.0",
  "Iron Liver",
  "Mantis Arm 2.0",
  "Pain Ward 2.0",
  "Quicksilver Legs 2.0",
  "Reflex Booster 2.0",
  "Resistance Booster 2.0",
  "Secondary Arm 1.0",
  "Secondary Heart",
  "Shapechanger 2.0",
  "Subdermal Armor 2.0",
  "Synthmuscle",
  "Ventilating Lungs",
  "Implant of Bodily Health",
  "Implant of Clear Thought",
  "Implant of Gainful Exercise",
  "Implant of Leadership and Influence",
  "Implant of Quickness of Action",
  "Implant of Understanding",
  "Manipulator Mechadendrite 2.0",
  "Synaptic Accelerator",
  "Tool Mechadendrite 2.0",
  "Barrier Device 2.0",
  "Blur Field Generator",
  "Cyberdeck 3.0",
  "Dead Space Earpiece",
  "Firearm Suppressor",
  "Kinetic Energy Dampening Device",
  "Photo-Goggles",
  "Scanner Device 2.0",
];

let VRAT = [
  "Blasting Eye 3.0",
  "Cat Eyes 3.0",
  "Cybernetic Spinal Cord",
  "Dog Ears 3.0",
  "Elemental Projector Arm 3.0",
  "Fortified Ankles & Tendons 3.0",
  "Gorilla Arms 3.0",
  "Mantis Arm 3.0",
  "Pain Ward 3.0",
  "Positronic Brain",
  "Quicksilver Legs 3.0",
  "Reflex Booster 3.0",
  "Resistance Booster 3.0",
  "Rocket Arm",
  "Secondary Arm 2.0",
  "Shapechanger 3.0",
  "Subdermal Armor 3.0",
  "Cybernetic Repulsor Unit",
  "Manipulator Mechadendrite 3.0",
  "Tool Mechadendrite 3.0",
  "Barrier Device 3.0",
  "Cyberdeck 4.0",
  "Firearm Silencer",
];

const itemClasses = [
  "Consumables",
  "Consumables",
  "Miscellaneous",
  "Miscellaneous",
  "Weapons",
  "Weapons",
  "Armor & Shields",
  "Armor & Shields",
  "Advanced Technology",
  "Advanced Technology",
];

const itemRarities = [
  "Uncommon",
  "Uncommon",
  "Uncommon",
  "Uncommon",
  "Rare",
  "Rare",
  "Rare",
  "Very Rare",
  "Very Rare",
  "Legendary",
];

function getRandomValueFromArray(array) {
  const randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
}

function generateRandomItemType() {
  const itemClass = getRandomValueFromArray(itemClasses);
  const itemRarity = getRandomValueFromArray(itemRarities);
  return `${itemRarity} ${itemClass}`;
}

function generateRandomItem(item) {
  let result;
  switch (item) {
    case "Uncommon Consumables":
      result = getRandomValueFromArray(UCC);
      break;
    case "Rare Consumables":
      result = getRandomValueFromArray(RAC);
      break;
    case "Very Rare Consumables":
      result = getRandomValueFromArray(VRC);
      break;
    case "Legendary Consumables":
      result = getRandomValueFromArray(LEC);
      break;
    case "Uncommon Miscellaneous":
      result = getRandomValueFromArray(UCM);
      break;
    case "Rare Miscellaneous":
      result = getRandomValueFromArray(RAM);
      break;
    case "Very Rare Miscellaneous":
      result = getRandomValueFromArray(VRM);
      break;
    case "Legendary Miscellaneous":
      result = getRandomValueFromArray(LEM);
      break;
    case "Uncommon Weapons":
      result = getRandomValueFromArray(UCW);
      break;
    case "Rare Weapons":
      result = getRandomValueFromArray(RAW);
      break;
    case "Very Rare Weapons":
      result = getRandomValueFromArray(VRW);
      break;
    case "Legendary Weapons":
      result = getRandomValueFromArray(LEW);
      break;
    case "Uncommon Armor & Shields":
      result = getRandomValueFromArray(UCAS);
      break;
    case "Rare Armor & Shields":
      result = getRandomValueFromArray(RAAS);
      break;
    case "Very Rare Armor & Shields":
      result = getRandomValueFromArray(VRAS);
      break;
    case "Legendary Armor & Shields":
      result = getRandomValueFromArray(LEAS);
      break;
    case "Uncommon Advanced Technology":
      result = getRandomValueFromArray(UCAT);
      break;
    case "Rare Advanced Technology":
      result = getRandomValueFromArray(RAAT);
      break;
    default:
      result = getRandomValueFromArray(VRAT);
      break;
  }
  return result;
}


  //Calculates Gatcha rolls
  function gatchaRoll(numItems) {
    const ul = document.getElementById("myUL");
    for (let i = 0; i < numItems; i++) {
      const li = document.createElement("li");
      let newItem = generateRandomItemType();
      if (newItem === "Legendary Advanced Technology") {
        newItem = "Very Rare Advanced Technology";
        i--;
      } else if (newItem.includes("Legendary")) {
        i--;
      }
      li.appendChild(document.createTextNode(generateRandomItem(newItem)));
      ul.appendChild(li);
    }
  }

// Displays a new list of rolls when clicking on the "Add" button
const ul = document.getElementById("myUL");
const input = document.getElementById("myInput");

function newElement() {
  const inputValue = input.value;
  if (!inputValue || isNaN(inputValue)) return alert("Please input a number!");
  ul.querySelectorAll("li").forEach(li => li.remove());
  gatchaRoll(inputValue);
  input.value = "";
}


